const actual = jest.requireActual('framer-motion');

module.exports = {
  ...actual,
  AnimatePresence: ({ children }) => children,
  motion: {
    div: 'div',
    span: 'span',
    button: 'button',
    img: 'img',
    svg: 'svg',
    path: 'path',
    section: 'section',
    article: 'article',
    aside: 'aside',
    header: 'header',
    footer: 'footer',
    nav: 'nav',
    main: 'main',
    h1: 'h1',
    h2: 'h2',
    h3: 'h3',
    h4: 'h4',
    h5: 'h5',
    h6: 'h6',
    p: 'p',
    a: 'a',
    ul: 'ul',
    ol: 'ol',
    li: 'li',
  },
  useReducedMotion: () => true,
  domAnimation: () => ({}),
};
